# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-25 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('deck_class', models.CharField(max_length=200)),
                ('text', models.CharField(max_length=200)),
                ('abilities_json', models.CharField(max_length=500)),
            ],
        ),
    ]
