# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-25 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hs_sim', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='cost',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='card',
            name='abilities_json',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='card',
            name='text',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
