# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-25 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hs_sim', '0002_fix_cost_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('text', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
            ],
        ),
    ]
