# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-25 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hs_sim', '0003_ability'),
    ]

    operations = [
        migrations.AddField(
            model_name='ability',
            name='value_spec',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
